# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b24d4095f17fe4fa80b3f5687fe858132d9d7495f3909c476feeffb7033eeffdf78ad64c6dbc48a66e77e73decaefd22d5f336575c08a24ed26063830fa88307

test:
  secret_key_base: 48f31b595f70b277cd55e676dfe2c31b4cfa85c5f289951bee49590612b1b23f67ab1974ac79cd052355f74af005fde2ae3e438079de412bd3c34edf54868be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
